openapi : "3.0.0"
info:
  title : Skill Exchange
  description : just using this for the first time
  version: 1.0.0
  contact:
    email: patelkrunal8469@gmail.com
    url: "https://krunal.com"

servers:
  - url: "http://locahost:3000"
    description: for testing purpose
  - url: "https://skillexchange-backend.onrender.com"
    description: Deployed version (uptodate)

paths:
  /user/login:
    post:
      requestBody:
        description: Enter deatils to login 
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                  description: Registered Email
                Password:
                  type: string
                  description: Your Password
      responses:
        '200': #status code
          description: A json object
          content: 
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: return type
                  message:
                    type: string
                    description: success message

